apiVersion: v1
kind: Pod
metadata:
  name: ssh-forwarder
spec:
  containers:
  - name: alpine-ssh
    image: your-registry/alpine-ssh
    command: ["/bin/sh", "-c"]
    args:
      - ssh -i /root/.ssh/id_rsa -N -L 8080:localhost:80 user@remote-host
    volumeMounts:
    - name: ssh-keys
      mountPath: /root/.ssh
      readOnly: true
  volumes:
  - name: ssh-keys
    secret:
      secretName: ssh-keys
