
apiVersion: v1
kind: Pod
metadata:
  name: ssh-forwarder
spec:
  containers:
  - name: alpine-ssh
    image: itsnet/alpine-autossh
    command: ["/bin/sh", "-c"]
    args:
      - autossh -M 0 -N -i /home/secure_link/.ssh/id_rsa -N -R localhost:8080:10.20.87.40:8080 secure_link@94.136.189.253 -p 59999
    volumeMounts:
    - name: ssh-keys
      mountPath: /home/secure_link/.ssh
      readOnly: true
  volumes:
  - name: ssh-keys
    secret:
      secretName: ssh-keys
