
apiVersion: v1
kind: Pod
metadata:
  name: ssh-forwarder
spec:
  containers:
  - name: alpine-ssh
    image: itsnet/alpine-autossh
    command: ["/bin/sh", "-c"]
    args:
      - autossh -M 0 -N -i /home/secure_link/.ssh/id_rsa -N -R vmi1763417:80:10.21.95.98:80 secure_link@94.136.189.253 -p 59999 -o UserKnownHostsFile=/home/secure_link/.ssh/known_hosts
    volumeMounts:
    - name: ssh-keys
      mountPath: /home/secure_link/.ssh
      readOnly: true
  volumes:
  - name: ssh-keys
    secret:
      secretName: ssh-keys
