
apiVersion: v1
kind: Pod
metadata:
  name: ssh-forwarder
spec:
  containers:
  - name: alpine-ssh
    image: itsnet/alpine-autossh
    command: ["/bin/sh", "-c"]
    args:
      - ssh -i /root/.ssh/id_rsa -N -R 8080:10.20.87.40:80 secure_link@94.136.189.253
    volumeMounts:
    - name: ssh-keys
      mountPath: /root/.ssh
      readOnly: true
  volumes:
  - name: ssh-keys
    secret:
      secretName: ssh-keys
